### PR TITLE
Feature/dp1000 optimise esc

### PR DESCRIPTION
**Pull request by Abner0907**
- [X] Power on, led will light immediately.
- [X] Do not allow to power off when armed(Ignore the power button).
- [X] log the motor status in the logfile; include:
- >
        state
        temperature
        rpm
        current
        esc_set

- [x] send out the motor status through mavlink2

### CODE REVIEW

**Comment by runinrain64** [comment]
- get_alt_above_ground_cm() exists in Copter and Mode class.
- APJ ID shall be 1039
- Because handle_rc_channels() is same to handle_rc_channels_override(), it could be better to use handle_rc_channels_override() instead of handle_rc_channels()

**Comment by Abner0907** [comment]
Thank you for your review. 
>     * get_alt_above_ground_cm() exists in Copter and Mode class.

 Done here https://github.com/CodevDynamics/Codev-APM/pull/4/commits/1cb86960730605413372b3552d471f4232ca90d8

>     * APJ ID shall be 1039
I want to our exist Dp1000's PX4  and APM are compatible. If two version, our engineer will confused with it. So we decide to use the same bootloader and ID in stm32f7 board for now. We will update in the next update in STM32H7 boards.

>     * Because handle_rc_channels() is same to handle_rc_channels_override(), it could be better to use handle_rc_channels_override() instead of handle_rc_channels()
Nope, they are different, They have different sysid, different decode function, we can not mix them together.

**Comment by runinrain64** [comment]
`they are different, They have different sysid, different decode function, we can not mix them together.`

 I got it.
I confirmed for merging.

**Comment by runinrain64** [comment]
I confirmed to merge.
- I  checked that duplicated function is removed.
- New Board ID will be used in Talon-A.
- And I am understood why there are two rc channels functions.
--

**Comment by Abner0907** [comment]
We have test this PR and performs good. Please refer the below data:

**Motor RPM**
Screenshot from 2021-08-18 18-28-33
**Motor Current**
Screenshot from 2021-08-18 18-27-33
**Motor Temperature**
Screenshot from 2021-08-18 18-26-41

**Pull request merged**
